# Generated by Django 4.2.10 on 2025-03-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_companyname_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
